import type { BuiltInTask } from '../catalog/types';

export const builtInCatalogVersion = 1;

export const builtInTasks: BuiltInTask[] = [
  {
    id: 'closeness-eye-contact-1',
    version: 1,
    source: 'built-in',
    title: 'Nur ansehen',
    text: 'Setzt euch bequem hin und schaut euch ruhig in die Augen. Sprecht erst wieder, wenn die Zeit vorbei ist.',
    mood: 'closeness',
    hint: 'Lächeln ist erlaubt. Wegschauen auch.',
  },
  {
    id: 'closeness-compliment-1',
    version: 1,
    source: 'built-in',
    title: 'Drei ehrliche Sätze',
    text: 'Sag der anderen Person drei Dinge, die du gerade an ihr magst oder schätzt.',
    mood: 'closeness',
  },
  {
    id: 'closeness-conversation-1',
    version: 1,
    source: 'built-in',
    title: 'Ein schöner Moment',
    text: 'Erzähle von einem gemeinsamen Moment, an den du gern zurückdenkst, und warum er dir wichtig ist.',
    mood: 'closeness',
  },
  {
    id: 'closeness-massage-1',
    version: 1,
    source: 'built-in',
    title: 'Ruhige Schultern',
    text: 'Massiere für die Zeit sanft Schultern oder Nacken der anderen Person.',
    mood: 'closeness',
    hint: 'Frage kurz nach, welcher Druck angenehm ist.',
  },
  {
    id: 'flirty-kissing-1',
    version: 1,
    source: 'built-in',
    title: 'Langsamer Kuss',
    text: 'Küsst euch langsam und spielerisch. Die aktive Person bestimmt Tempo und Pausen.',
    mood: 'flirty',
  },
  {
    id: 'flirty-touch-1',
    version: 1,
    source: 'built-in',
    title: 'Fingerspitzen',
    text: 'Berühre Arm, Hand oder Rücken der anderen Person mit langsamen, leichten Bewegungen.',
    mood: 'flirty',
    hint: 'Bleibt bei Berührungen, die sich für euch beide passend anfühlen.',
  },
  {
    id: 'flirty-fantasy-1',
    version: 1,
    source: 'built-in',
    title: 'Ein Wunsch',
    text: 'Beschreibe einen kleinen Wunsch für euren Abend, ohne dass daraus eine Verpflichtung entsteht.',
    mood: 'flirty',
  },
  {
    id: 'flirty-roleplay-1',
    version: 1,
    source: 'built-in',
    title: 'Neue Begegnung',
    text: 'Tut für eine Minute so, als würdet ihr euch gerade erst kennenlernen und miteinander flirten.',
    mood: 'flirty',
  },
  {
    id: 'intimate-touch-1',
    version: 1,
    source: 'built-in',
    title: 'Nähe führen',
    text: 'Die aktive Person führt die Hand der anderen Person zu einer Berührung, die gerade willkommen ist.',
    mood: 'intimate',
    hint: 'Jede Person kann jederzeit stoppen oder ändern.',
  },
  {
    id: 'intimate-kissing-1',
    version: 1,
    source: 'built-in',
    title: 'Intensiver küssen',
    text: 'Küsst euch intensiver und achtet bewusst auf Atem, Tempo und Reaktionen.',
    mood: 'intimate',
  },
  {
    id: 'intimate-fantasy-1',
    version: 1,
    source: 'built-in',
    title: 'Mehr davon',
    text: 'Sag leise, wovon du gerade mehr möchtest, und gib der anderen Person Raum, darauf zu reagieren.',
    mood: 'intimate',
  },
  {
    id: 'intimate-massage-1',
    version: 1,
    source: 'built-in',
    title: 'Warme Hände',
    text: 'Massiere eine Stelle, die sich für euch beide passend und angenehm anfühlt.',
    mood: 'intimate',
  },
];
